"""Initial create weather_data table

Revision ID: 77c90cb07de0
Revises: 
Create Date: 2026-05-05 12:14:48.582792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c90cb07de0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('wind_degree', sa.Integer(), nullable=False),
    sa.Column('wind_kph', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.Enum('N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW', name='winddirection'), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.Column('sunrise', sa.Time(), nullable=True),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('gust_kph', sa.Float(), nullable=True),
    sa.Column('gust_mph', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_id'), 'weather_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_id'), table_name='weather_data')
    op.drop_table('weather_data')
    # ### end Alembic commands ###
