"""refactor wind data to separate table

Revision ID: 8cbae7b22e88
Revises: 77c90cb07de0
Create Date: 2026-05-05 13:03:41.649752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cbae7b22e88'
down_revision: Union[str, Sequence[str], None] = '77c90cb07de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wind_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.Column('wind_degree', sa.Integer(), nullable=False),
    sa.Column('wind_kph', sa.Float(), nullable=False),
    sa.Column('wind_direction',
              sa.Enum('N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW',
                      name='winddirection', create_type=False), nullable=False),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('gust_kph', sa.Float(), nullable=True),
    sa.Column('gust_mph', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['weather_id'], ['weather_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weather_id')
    )

    op.execute(
        """
        INSERT INTO wind_data (weather_id, wind_degree, wind_kph, wind_direction, wind_mph, gust_kph, gust_mph)
        SELECT id, wind_degree, wind_kph, wind_direction, wind_mph, gust_kph, gust_mph
        FROM weather_data;
        """
    )

    op.create_index(op.f('ix_wind_data_id'), 'wind_data', ['id'], unique=False)
    op.drop_column('weather_data', 'wind_direction')
    op.drop_column('weather_data', 'wind_mph')
    op.drop_column('weather_data', 'gust_mph')
    op.drop_column('weather_data', 'wind_kph')
    op.drop_column('weather_data', 'gust_kph')
    op.drop_column('weather_data', 'wind_degree')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('wind_degree', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('weather_data', sa.Column('gust_kph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather_data', sa.Column('wind_kph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('weather_data', sa.Column('gust_mph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather_data', sa.Column('wind_mph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather_data', sa.Column('wind_direction', postgresql.ENUM('N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW', name='winddirection'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_wind_data_id'), table_name='wind_data')
    op.drop_table('wind_data')
    # ### end Alembic commands ###
