"""add should_go_out column

Revision ID: f3428c9adf78
Revises: 8cbae7b22e88
Create Date: 2026-05-05 13:15:03.015319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3428c9adf78'
down_revision: Union[str, Sequence[str], None] = '8cbae7b22e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wind_data', sa.Column('should_go_out', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wind_data', 'should_go_out')
    # ### end Alembic commands ###
